services:
  source-nw:
    image: arm64v8/postgres:alpine
    environment:
      - POSTGRES_USER=northwind
      - POSTGRES_PASSWORD=nw1234
      - POSTGRES_DB=northwind
    ports:
      - "5435:5432"
    volumes:
      - ./pg-nw:/docker-entrypoint-initdb.d
  dwh:
    image: arm64v8/postgres:alpine
    environment:
      - POSTGRES_USER=dwh
      - POSTGRES_PASSWORD=dwh1234
      - POSTGRES_DB=dwh
    ports:
      - "5433:5432"